version: '3'
services:
  db:
    image: prashantjain31/database
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  backend:
    image: prashantjain31/backend
    # volumes:
    #   - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
  
  frontend:
    image: prashantjain31/frontend
    ports:
      - "3000:3000"
      
volumes:
  db_data:
