# Use the official MySQL image as the base
FROM mysql:5.7

# Set environment variables
ENV MYSQL_ROOT_PASSWORD=prashantjain
ENV MYSQL_DATABASE=spe_project
ENV MYSQL_USER=prashantjain
ENV MYSQL_PASSWORD=prashantjain

# Expose the default MySQL port
EXPOSE 3306

# Start the MySQL server
CMD ["mysqld"]